version: '3.0'
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongoDB:27017
      DB_NAME: DigitalerZwillingHerne
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: "mongoDB"
    image: mongo:4.4.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: {}